name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get OAuth Token
        id: get-token
        run: |
          response=$(curl -s -X POST -u "${{ secrets.CLIENT_ID }}:${{ secrets.CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" \
            https://github.com/login/oauth/access_token)
          echo "::set-output name=token::$(echo $response | jq -r '.access_token')"

      - name: Post comment
        env:
          OAUTH_TOKEN: ${{ steps.get-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -H "Authorization: token $OAUTH_TOKEN" \
               -X POST \
               -d '{"body": "Thank you for your contribution!"}' \
               https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_EVENT_PULL_REQUEST_NUMBER/comments
