name: Comment on PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  comment:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write
    #   issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Post comment
        run: |
          curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ steps.get_workflow_token.outputs.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -X POST \
              -d '{"body": "Thank you for your contribution!"}' \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
