name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Post comment
        env:
          APP_ID: ${{ secrets.APP_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          node -e "
          const { Octokit } = require('@octokit/rest');
          const { createAppAuth } = require('@octokit/auth-app');

          const octokit = new Octokit({
            authStrategy: createAppAuth,
            auth: {
              appId: process.env.APP_ID,
              privateKey: process.env.PRIVATE_KEY,
              clientId: process.env.CLIENT_ID,
              clientSecret: process.env.CLIENT_SECRET,
              installationId: process.env.GITHUB_INSTALLATION_ID,
            },
          });

          const comment = 'Thank you for your contribution!';
          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
          const issue_number = process.env.GITHUB_EVENT_PULL_REQUEST_NUMBER;

          octokit.issues.createComment({
            owner,
            repo,
            issue_number,
            body: comment,
          });
          "
