name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post comment
        run: |
          curl -H "Authorization: token ${{ github.token }}" \
               -X POST \
               -d '{"body": "Thank you for your contribution!"}' \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
